version: '3.8'

services:
  postgres:
    container_name: auction_backend
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: auction_db
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres